/**
 * API for remove-gene filter
 * API for remove-gene filter.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */

package sharpener.tcrd.model

case class Attribute(
  name: String,
    value: String,
    source: Option[String]
  )
