/**
 * API for gene-list transformers
 * API for gene-list transformers.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */


package sharpener.tcrd.server.api

import sharpener.tcrd.model.Gene_info
import sharpener.tcrd.model.Transformer_info
import sharpener.tcrd.model.Transformer_query

import java.io.File

import org.scalatra.ScalatraServlet
import org.scalatra.swagger._
import org.json4s._
import org.json4s.JsonDSL._
import org.scalatra.json.{ JValueResult, JacksonJsonSupport }
import org.scalatra.servlet.{ FileUploadSupport, MultipartConfig, SizeConstraintExceededException }

import scala.collection.JavaConverters._

class TransformerApi(implicit val swagger: Swagger) extends ScalatraServlet
  with FileUploadSupport
  with JacksonJsonSupport
  with SwaggerSupport {
  protected implicit val jsonFormats: Formats = DefaultFormats

  protected val applicationDescription: String = "TransformerApi"

  before() {
    contentType = formats("json")
    response.headers += ("Access-Control-Allow-Origin" -> "*")
  }
  

  val transformPostOperation = (apiOperation[List[Gene_info]]("transformPost")
      summary ""
      parameters(bodyParam[Transformer_query]("query").description(""))
  )

  post("/transform",operation(transformPostOperation)) {
    
    
          val query = parsedBody.extract[Transformer_query]

    println("query: " + query)
  }

  

  val transformerInfoGetOperation = (apiOperation[Transformer_info]("transformerInfoGet")
      summary "Retrieve transformer info"
      parameters()
  )

  get("/transformer_info",operation(transformerInfoGetOperation)) {
  }

}
